### ISSUE TITLE
AttributeError: 'int' object has no attribute 'find' for TPB/KAT

### ISSUE THREAD

**Issue by odgalvin** [kryptxy/torrench#26] opened 2017-09-24 21:53 UTC
I have torrench 1.0.53 installed via pip on Parabola (Arch) Linux. I get this error when attempting torrench -t "test" and when attempting torrench -k "test" respectively:

[https://pastebin.com/aXb4kJU1](https://pastebin.com/aXb4kJU1)

DistroWatch, SkyTorrents, Nyaa and Xbit work fine.

**Comment by kryptxy** [comment] 2017-09-25 00:53
Working for me..
Try re-setting up the config.ini file. If it still doesn't work - 

- See if ```https://proxybay.one``` opens in your browser?
- Please post the config.ini file

**Comment by odgalvin** [comment] 2017-09-25 10:24
I haven't modified the config.ini file from the one you supplied, here's the values I have set:
[https://pastebin.com/1Wf0916Y](https://pastebin.com/1Wf0916Y)

proxybay.one doesn't work for me, I think it's blocked as I'm in the UK, as it works via Tor.
torify torrench -t "test" gives me:
[https://pastebin.com/Cd1667Ly](https://pastebin.com/Cd1667Ly)

Again, "torify torrench" works for to Skytorrents etc.

**Comment by datafanatic** [comment] 2017-09-25 10:41
Are you using torify in all the requests? Or were you using it just for testing?

**Comment by kryptxy** [comment] 2017-09-25 12:46
> proxybay.one doesn't work for me, I think it's blocked as I'm in the UK, as it works via Tor.
torify torrench -t "test" gives me:
https://pastebin.com/Cd1667Ly

Please attach the log file.

**Comment by odgalvin** [comment] 2017-09-25 14:29
@datafanatic I only used torify once I saw the initial error and that I couldn't access proxybay.one, the errors I initially posted were without tor. I regularly use tor to access torrent sites though, due to the censorship, and torrench works fine with or without torify except for KAT/TPB.

@kryptxy Log from torify torrench -t "test":
https://pastebin.com/t0gFD7Dk

**Comment by kryptxy** [comment] 2017-09-25 15:02
Both ```https://proxybay.one``` and ```https://thepiratebay.org``` returned status 403.
Are they accessible from browser?
Also, since you are using TOR, you might consider using TPB ```.onion``` site. Add the .onion site to ```config.ini``` file.
(Like ```TPB_URL = <.onion> <other_sites>```)

I haven't tested it myself, but I think it should work.

**Comment by datafanatic** [comment] 2017-09-25 15:11
@odgalvin I see. I asked because it could be that the website was redirecting to a CloudFlare captcha page, which is what happened when I tried `torify curl https://thepiratebay.org`. 
Also it should be noted that as of right now the TPB server has gone offline, and it has been for a while now. I think that may be the problem.

When (and if) it comes back, try again and report here your results.

**Comment by datafanatic** [comment] 2017-09-25 15:45
Conveniently enough, the website has just come back to life.

**Comment by datafanatic** [comment] 2017-09-26 20:27
Hi @odgalvin, was your problem fixed?

**Comment by kryptxy** [comment] 2017-10-05 05:00
Closing (assuming the issue is resolved). If it isn't, post a reply and it will be re-opened.

**Closed by kryptxy** 2017-10-05 05:00 UTC

**Comment by Gillinghammer** [comment] 2018-01-23 20:02
Having this error myself after I tried to port my old config to a new installation of Mac High Sierra OS. Any ideas on how to fix? 

Never had a problem reaching TPB before, but now it will try the whole list and fail.

**Comment by datafanatic** [comment] 2018-01-23 21:14
@Gillinghammer Hi, could you please post your config file? This problem generally happens when the website is offline. Perhaps we ought to handle the exception ourselves in the future.

**Comment by Gillinghammer** [comment] 2018-01-24 11:22
Looks like TPB proxy sites might have been down, as I get results now, although not as quickly as I did before moving my configuration to this new system.

Kickass torrents used to work but now that spits out an error:
`AttributeError: 'int' object has no attribute 'find'`

When I attempt to load the torrent in my client, it gives me:
`[ERROR]: [Errno 2] No such file or directory: 'transmission-remote': 'transmission-remote'`
(is there a command line version I need to install or link to ?)

my config.ini
https://pastebin.com/jjYfqCn2
